sonar.projectKey=contact-management-system
sonar.projectName=Contact Management System
sonar.projectVersion=0.0.1-SNAPSHOT

sonar.sourceEncoding=UTF-8
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/webapp/my-app/node_modules/**,**/webapp/my-app/dist/**
